name: Docker Build & Publish

on: [push]

env:
  REGISTRY: opswat
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Print branch name
        run: echo "This job's status is ${{ github.ref }}."
