name: Docker Build & Publish

on:
  push:
    tags: 
      - '*'

env:
  REGISTRY: opswat
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}

      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{  github.ref_name }}
          build-args: version=${{  github.ref_name }}
