name: Docker Build & Publish

# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app


      - run: echo "tag $steps.meta.outputs.tags"
      - run: echo "label $steps.meta.outputs.labels"

