name: Docker Build & Publish

# on:
#   push:
#     branches:
#       - main

on: [push]      

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Docker build started."
      - run: echo "Docker image has been generated"
      - run: echo "Docker image has been published on DockerHub"
      - run: echo "dockeruser is $DOCKERHUB_USER"

