name: Docker Build & Publish

# on:
#   push:
#     branches:
#       - main
on: [push]

env:
  REGISTRY: opswat
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - run: echo "tag ${{ steps.meta.outputs.tags }}"
      - run: ${{ steps.meta.outputs.tags }}

