name: Docker Build & Publish

on: [push]

env:
  REGISTRY: opswat
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  dockerbuild:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Actual branch is ${{ github.ref }}."
  print_name:
    if: github.ref != 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Actual branch is ${{ github.ref }}."
