name: Docker Build & Publish

on:
  push:
    tags: 
    #  Assemblyline tags start with 4.4. or 4.5.
      - '4.5.*'

env:
  REGISTRY: opswat
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{  github.ref_name }}
          build-args: version=${{  github.ref_name }}
  
