name: Docker Build & Publish

on:
  push:
    tags: 
      - '*'

env:
  REGISTRY: opswat
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{  github.ref_name }}
          build-args: version=${{  github.ref_name }}
  print_branch_name:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Print branch name
        run: echo "Actual branch is ${{ github.ref }}."
  
