name: Docker Build & Publish

# on:
#   push:
#     branches:
#       - main
on: [push]
# on:
#   push:
#     tags: 
#       - '*'

env:
  REGISTRY: opswat
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}


      - run: echo "imagename ${{ env.REPO_NAME }}"

      - run: echo "TAG ${{  github.ref_name }}"


      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ${{  github.ref_name }}
      #     build-args: version=${{  github.ref_name }}
