name: Run Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'          
      # - name: Install pipenv
      #   working-directory: ./tests
      #   run: pip install pipenv
      # - name: Install dependencies
      #   working-directory: ./tests
      #   run: pipenv install 
      # - name: Run tests
      #   working-directory: ./tests
      #   run: pipenv run pytest -v          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest 
          pytest filescan_sandbox_test.py 
