name: Run Tests

on:
  push:
    tags: 
      - '*'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install libfuzzy
        working-directory: ./tests
        run: |
          sudo apt-get update
          sudo apt-get -y install libfuzzy-dev
      - name: Install dependencies
        working-directory: ./tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: ./tests
        run: |
          pytest -v
