name: Run Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        working-directory: ./tests
        run: |
          pipenv install 
          pipenv run pytest -v

